<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dataTables = [
            [
                'id' => 26,
                'user_id' => 1,
                'book_id' => 5,
                'add_date' => '2025-11-27',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => 0,
                'state' => 'favorite',
                'property' => 1,
                'created_at' => '2025-11-27 19:45:45',
                'updated_at' => '2025-11-28 16:35:02',
            ],
            [
                'id' => 27,
                'user_id' => 1,
                'book_id' => 1,
                'add_date' => '2025-11-27',
                'read_date' => '2025-11-12',
                'comment' => 'EStá bastante bien!!',
                'rating' => 5,
                'state' => 'borrowed',
                'property' => 1,
                'created_at' => '2025-11-27 23:23:08',
                'updated_at' => '2025-11-30 00:45:41',
            ],
            [
                'id' => 28,
                'user_id' => 1,
                'book_id' => 2,
                'add_date' => '2025-11-27',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => 5,
                'state' => 'favorite',
                'property' => 1,
                'created_at' => '2025-11-27 23:23:23',
                'updated_at' => '2025-11-28 16:35:21',
            ],
            [
                'id' => 29,
                'user_id' => 1,
                'book_id' => 6,
                'add_date' => '2025-11-27',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => 4,
                'state' => 'favorite',
                'property' => 1,
                'created_at' => '2025-11-27 23:32:36',
                'updated_at' => '2025-11-28 16:34:45',
            ],
            [
                'id' => 31,
                'user_id' => 2,
                'book_id' => 1,
                'add_date' => '2025-11-28',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 0,
                'created_at' => '2025-11-28 17:15:05',
                'updated_at' => '2025-11-28 17:15:05',
            ],
            [
                'id' => 32,
                'user_id' => 2,
                'book_id' => 10,
                'add_date' => '2025-11-28',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => 3,
                'state' => 'sold',
                'property' => 1,
                'created_at' => '2025-11-28 17:15:11',
                'updated_at' => '2025-11-28 22:19:31',
            ],
            [
                'id' => 33,
                'user_id' => 2,
                'book_id' => 15,
                'add_date' => '2025-11-28',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => 5,
                'state' => 'favorite',
                'property' => 1,
                'created_at' => '2025-11-28 17:18:34',
                'updated_at' => '2025-11-28 17:19:11',
            ],
            [
                'id' => 34,
                'user_id' => 2,
                'book_id' => 2,
                'add_date' => '2025-11-28',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 0,
                'created_at' => '2025-11-28 17:18:41',
                'updated_at' => '2025-11-28 17:18:41',
            ],
            [
                'id' => 35,
                'user_id' => 2,
                'book_id' => 5,
                'add_date' => '2025-11-28',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 0,
                'created_at' => '2025-11-28 17:18:48',
                'updated_at' => '2025-11-28 17:18:48',
            ],
            [
                'id' => 36,
                'user_id' => 2,
                'book_id' => 6,
                'add_date' => '2025-11-28',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => 0,
                'state' => 'favorite',
                'property' => 1,
                'created_at' => '2025-11-28 17:28:40',
                'updated_at' => '2025-11-28 17:44:31',
            ],
            [
                'id' => 37,
                'user_id' => 2,
                'book_id' => 7,
                'add_date' => '2025-11-28',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 0,
                'created_at' => '2025-11-28 17:28:56',
                'updated_at' => '2025-11-28 17:28:56',
            ],
            [
                'id' => 38,
                'user_id' => 2,
                'book_id' => 17,
                'add_date' => '2025-11-28',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 1,
                'created_at' => '2025-11-28 17:33:50',
                'updated_at' => '2025-11-28 17:33:50',
            ],
            [
                'id' => 39,
                'user_id' => 2,
                'book_id' => 14,
                'add_date' => '2025-11-28',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 1,
                'created_at' => '2025-11-28 22:24:06',
                'updated_at' => '2025-11-28 22:24:06',
            ],
            [
                'id' => 40,
                'user_id' => 1,
                'book_id' => 3,
                'add_date' => '2025-11-29',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 1,
                'created_at' => '2025-11-29 20:04:36',
                'updated_at' => '2025-11-29 20:04:36',
            ],
            [
                'id' => 41,
                'user_id' => 1,
                'book_id' => 11,
                'add_date' => '2025-11-29',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 1,
                'created_at' => '2025-11-29 21:59:00',
                'updated_at' => '2025-11-29 21:59:00',
            ],
            [
                'id' => 43,
                'user_id' => 1,
                'book_id' => 14,
                'add_date' => '2025-11-30',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 0,
                'created_at' => '2025-11-30 01:17:01',
                'updated_at' => '2025-11-30 01:17:01',
            ],
            [
                'id' => 44,
                'user_id' => 1,
                'book_id' => 10,
                'add_date' => '2025-11-30',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 1,
                'created_at' => '2025-11-30 01:17:34',
                'updated_at' => '2025-11-30 01:17:34',
            ],
            [
                'id' => 45,
                'user_id' => 1,
                'book_id' => 12,
                'add_date' => '2025-11-30',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 1,
                'created_at' => '2025-11-30 01:17:40',
                'updated_at' => '2025-11-30 01:17:40',
            ],
            [
                'id' => 46,
                'user_id' => 1,
                'book_id' => 13,
                'add_date' => '2025-11-30',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 1,
                'created_at' => '2025-11-30 01:17:46',
                'updated_at' => '2025-11-30 01:17:46',
            ],
            [
                'id' => 47,
                'user_id' => 1,
                'book_id' => 15,
                'add_date' => '2025-11-30',
                'read_date' => NULL,
                'comment' => NULL,
                'rating' => NULL,
                'state' => NULL,
                'property' => 1,
                'created_at' => '2025-11-30 01:30:22',
                'updated_at' => '2025-11-30 01:30:22',
            ]
        ];
        
        DB::table("book_user")->insert($dataTables);
    }
}